// <auto-generated />
namespace WindowsEFEscuela.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class dbsetagregado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbsetagregado));
        
        string IMigrationMetadata.Id
        {
            get { return "202301162020543_db-set-agregado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
